language: ruby
dist: trusty
rvm:
  - 2.5.3
before_install:
  - gem install bundler -v '2.0.2'
before_script:
  - gem update --system
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
script:
  # - bundle exec rake ci:tests
services:
  - postgresql
notifications:
  email: false